# Generated by Django 4.2.20 on 2025-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_customuser_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
