# Generated by Django 4.2.20 on 2025-04-18 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_course_teacher_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('quiz', 'Quiz'), ('project', 'Project'), ('homework', 'Homework'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course', 'grade_type')},
        ),
    ]
