# Generated by Django 4.2.20 on 2025-04-26 05:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_grade_unique_together_grade_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_teacher': True}, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('exam', 'Экзамен'), ('quiz', 'Тест'), ('project', 'Проект'), ('homework', 'Домашка'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
    ]
